### ISSUE TITLE
Evaluate appimaged and AppImage plugin

### ISSUE THREAD

**Issue by tim-sueberkrueb** [tim-sueberkrueb/ubup#4]
Idea: Add plugin that
* [ ] installs appimaged (if not already installed) to the recommended location
* [ ] allows installing a list of AppImages (remote, local (?))

Open questions:
* Recommended location for installing AppImages? User choice?
* How to register AppImages with appimaged?
* Further enhancements to download latest GitHub release (-> separate plugin)?

**Comment by probonopd** [comment]
> Recommended location for installing AppImages? User choice?

Here are the directories watched by `appimaged`:
https://github.com/AppImage/AppImageKit#appimaged-usage

> How to register AppImages with appimaged?

Just place them into one of the watched directories.

**Comment by tim-sueberkrueb** [comment]
Thanks @probonopd!

**Comment by tim-sueberkrueb** [comment]
It is actually easy enough to download and install `appimaged` and place AppImages in the correct locations with the existing plugins. There is no real need for a plugin here.
